### PR TITLE
fix(profiles): getPathToContributor does not include path prefix

### LINKED ISSUE #1242: Profile pages on Dismoi.io answer with "Page introuvable"

### PR DESCRIPTION
**Pull request by JalilArfaoui**
Fixes #1242

### CODE REVIEW

File: src/libs/facets/getPathPrefix.ts [hunk 1]
```diff
@@ -0,0 +1,5 @@
+import { i18n } from 'i18next';
+import { getFacet } from './getFacet';
+
+export const getPathPrefix = (i18n: i18n): string =>
+  getFacet() === 'lmel' ? '' : `/${i18n.language}`;
```
Comment (lutangar) [inline src/libs/facets/getPathPrefix.ts:5]: It seems it was this way before BUT feels akward to  have a `/` in one case and none in the other...

File: src/app/profiles/App/pathToContributor.ts [hunk 2]
```diff
@@ -1,11 +1,12 @@
 import slugify from 'slugify';
 import i18n from 'i18next';
 import { Contributor } from 'libs/domain/contributor';
+import { getPathPrefix } from '../../../libs/facets/getPathPrefix';
 
 const pathToContributor = (contributor: Contributor) => {
-  return `${i18n.t('path.profiles.contributors')}/${contributor.id}/${slugify(
-    contributor.name
-  )}`;
+  return `${getPathPrefix(i18n)}${i18n.t('path.profiles.contributors')}/${
```
Comment (lutangar) [inline src/app/profiles/App/pathToContributor.ts:7]: For complex path joining it would be way cooler to use smthing like node's `path.join`.
Here we don't which part come with a `/` or not...
Maybe smthing could be crafted with the [URL API](https://developer.mozilla.org/fr/docs/Web/API/URL) instead?

File: src/libs/facets/getPathPrefix.ts (hunk 1 above)
Comment (JalilArfaoui) [reply src/libs/facets/getPathPrefix.ts:5]: It's because we add a whole segment in one case, and not in the other … `/fr/something` versus `/something` …

File: src/app/profiles/App/pathToContributor.ts (hunk 2 above)
Comment (JalilArfaoui) [reply src/app/profiles/App/pathToContributor.ts:7]: We can't use `path` since we’re browser side, and `URL` constructor doesn’t seem to have a builin parts joining feature … 

I’m lookinq at https://www.npmjs.com/package/join-path …

Comment (JalilArfaoui) [reply src/app/profiles/App/pathToContributor.ts:7]: Nope, it also needs `path` … I’m looking at https://www.npmjs.com/package/join-url

Comment (lutangar) [reply src/app/profiles/App/pathToContributor.ts]: Love it!
