### PR TITLE
fix(useContributorFilter): reset contributor on change tab

### LINKED ISSUE #1141: Proding 3.88.0 : could not follow neither unfollow a contributor on his contributor page during many seconds - it was only possible on page listing profiles
Probably linked to https://github.com/dis-moi/extension/issues/1132 
I close and we will see if it back after #1132 is solved

### PR DESCRIPTION
**Pull request by gregoirelacoste**

### CODE REVIEW

File: src/app/profiles/hooks/useContributorsFilters.ts [hunk 1]
```diff
@@ -24,7 +24,13 @@ function useContributorsFilters(
     );
 
   useEffect(() => {
-    if (selectedCategory && selectedCategory === ALL) {
+    console.log(
```
Comment (lutangar) [inline src/app/profiles/hooks/useContributorsFilters.ts:27]: We shouldn't log anything in the content script.
We may log things in the background using the appropriate `logger` service.

**Review by lutangar — CHANGES_REQUESTED** [review]

**Review by JalilArfaoui — APPROVED** [review]
Seems fine... Apart from the forgotten `console.logs`
