### PR TITLE
fix(search): responsive and accent

### LINKED ISSUE #1005: Search engine on list of profiles pages
Main story : If I discovered DisMoi through a profile I want find it back after I installed DisMoi

**Remarque 1 :**  Si l'utilisateur recherche de façon libre, au moment où il valide, la page de résultat chargée décoche automatiquement tous les filtres 
CàD pas de combinaison entre filtre et recherche libre

**Remarque 2 :**  Pas de recherche libre sur mobile pour l'instant

### LINKED ISSUE #1082: Ignore accents in seach results on profile list page
Problem : If I type "rhone" in serach engine, "Le Même en Rhône Alpes" does not appear in results.

### PR DESCRIPTION
**Pull request by gregoirelacoste**
closes #1082
closes #1005

### CODE REVIEW

File: src/libs/utils/getSearch.ts [hunk 1]
```diff
@@ -4,17 +4,23 @@ const getSearch = (
   value: string,
   contributors: StatefulContributor[]
 ): StatefulContributor[] => {
+  const normalizeText = (string: string) =>
```
Comment (lutangar) [inline src/libs/utils/getSearch.ts:7]: Did you add a test case for the accent problem?

Comment (lutangar) [reply src/libs/utils/getSearch.ts:7]: Btw, this function should be defined outside of the `getSearch` function scope to be easily tested
(not saying it must be tested but it could)

File: src/components/molecules/Search/Search.tsx [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+interface SearchProps {
+  categoriesLoading: trilean;
+  categories: Record<string, string>;
+  setFilter: (value: string) => void;
+  handleChangeSearchContributors: (
+    e: React.ChangeEvent<HTMLInputElement>
+  ) => void;
+}
+
+const Search = ({
```
Comment (lutangar) [inline src/components/molecules/Search/Search.tsx:79]: Didn't see a story for the search component.

File: src/libs/utils/getSearch.ts (hunk 1 above)
Comment (JalilArfaoui) [reply src/libs/utils/getSearch.ts:7]: Little simplification :

```ts
const unaccent = (string: string) =>
    string
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '');

const getSearch = (
  search: string,
  contributors: StatefulContributor[]
): StatefulContributor[] => {
  if (!search) return contributors;

  const searchExpression = new RegExp(
    unaccent(search).split(' ').replace(/.+/g, '(?=.*$&)').join(''),
    'gi'
  );

  return contributors.filter(({ name, intro }) => searchExpression.test(unaccent(`${name} ${intro}`)))
}
```

- Extract `unaccent` as suggested by @lutangar 
- Avoid filtering if no search by returning immediateliy
- insensitive regex instead of uppercase modification
- a bit of renaming

Comment (JalilArfaoui) [reply src/libs/utils/getSearch.ts:7]: There is also https://www.npmjs.com/package/remove-accents FYI

**Comment by gregoirelacoste** [comment]
@lutangar @JalilArfaoui ok for your changes. Also, I had to change the Subscription component which had a problem because of the new hook and the `findContributorIn` function which generated a render loop

File: src/app/profiles/App/Pages/Profiles/List/ProfileList.tsx [hunk 3]
```diff
@@ -21,8 +21,7 @@ import NotConnectedPopin, {
 } from '../NotConnectedPopin';
 import onContributorExampleClick from '../../../onContributorExampleClick';
 import { ContextPopinState } from '../../../../store/reducers/contextPopin.reducer';
-import { Input, Select } from '../../../../../../components/atoms/Forms';
-import { ALL } from '../../../../../../components/molecules/Filters/RadiosFilters';
+import Search from '../../../../../../components/molecules/Search/Search';
```
Comment (lutangar) [inline src/app/profiles/App/Pages/Profiles/List/ProfileList.tsx:24]: Prefer absolute imports

**Comment by lutangar** [comment]
Could you include my comments from https://github.com/dis-moi/extension/pull/1059 in this PR please?

**Comment by gregoirelacoste** [comment]
@lutangar done

File: src/libs/utils/getSearch.ts (hunk 1 above)
Comment (lutangar) [reply src/libs/utils/getSearch.ts]: > Did you add a test case for the accent problem?

Didn't see the accent test :p

Comment (gregoirelacoste) [reply src/libs/utils/getSearch.ts]: later ;)

File: src/app/profiles/App/Pages/Subscriptions/Subscriptions.tsx [hunk 4]
```diff
@@ -11,25 +11,27 @@ import { TwoColumns } from 'components/atoms';
...
-import useContributorsFilters from 'app/profiles/App/useContributorsFilters';
+import useContributorsFilters from 'app/profiles/hooks/useContributorsFilters';
 import {
   ContributorExampleLink,
   ContributorProfileListItem
 } from '../Profiles/List/ProfileList';
 import { Aside, MainCol } from '../Profiles/Profile/Profile';
 import ProfileTabs from '../../ProfileTabs';
 import { Arrow } from '../../../../../components/atoms/icons';
+import Search from '../../../../../components/molecules/Search/Search';
```
Comment (lutangar) [inline src/app/profiles/App/Pages/Subscriptions/Subscriptions.tsx:22]: Prefer absolute import...

File: src/libs/utils/getSearch.ts (hunk 1 above)
Comment (lutangar) [reply src/libs/utils/getSearch.ts]: Ok I'll approve later then... :door:

File: src/app/profiles/App/Pages/Subscriptions/Subscriptions.tsx (hunk 4 above)
Comment (gregoirelacoste) [reply src/app/profiles/App/Pages/Subscriptions/Subscriptions.tsx:22]: we need to setup eslint to do that automatically...

Comment (lutangar) [reply src/app/profiles/App/Pages/Subscriptions/Subscriptions.tsx]: Yeah I know, but I failed to do so... here is some background:
https://github.com/dis-moi/extension/pull/900#issue-614630571

File: src/libs/utils/getSearch.ts (hunk 1 above)
Comment (gregoirelacoste) [reply src/libs/utils/getSearch.ts]: done...

**Review by lutangar — APPROVED** [review]
