### PR TITLE
fix: extension completely hangs after 6|10 retries 

### LINKED ISSUE #861: Chrome extension blocked on Chloé and Maarten's computers and probably others
**Describe the bug**
On Chloé's computer on every page, DisMoi is grey : no notice, no interaction possible. 
It's possible she had same problem on other computer, but not sure.

**Vidéo**
This Vidéo shows bug but also informations from extension background.
It has been recorded during our call : https://drive.google.com/file/d/1kqcqnqXR5raQYVGhpUAObLNK6Dc7tUTC/view

**To Reproduce**
I don't know

**Desktop):**
 - OS: Windows
 - Browser : Chrome 
 - Version : 89 0.4389 90

**Extension**
- Version : 3.61
- Installed from store
- Installation date : don't know, probably recently
It's a new computer she just bought, refurbed.

### PR DESCRIPTION
**Pull request by JalilArfaoui**
fix: extension completely hangs after 6|10 retries of fetching contributors|matching-contexts

fixes #861

### CODE REVIEW

File: src/app/sagas/effects/callAndRetry.ts [hunk 1]
```diff
@@ -36,7 +35,7 @@ export const createCallAndRetry = (options: Partial<Options>) =>
         if ('onError' in o && o.onError) {
           yield call(o.onError, e, attemptNumber);
         }
-        if (attemptNumber < o.maximumAttempts) {
+        if (!o.maximumAttempts || attemptNumber < o.maximumAttempts) {
```
Comment (felix-lambert) [inline src/app/sagas/effects/callAndRetry.ts:38]: What us o referring to? Maybe we could be more explicit with the naming?

**Review by felix-lambert — COMMENTED** [review]
Just a review based on naming. It's of course a non blocking one

File: src/app/sagas/effects/callAndRetry.ts (hunk 1 above)
Comment (JalilArfaoui) [reply src/app/sagas/effects/callAndRetry.ts]: You’re right, I’ve renamed it to `options`

**Review by felix-lambert — APPROVED** [review]

**Review by lutangar — APPROVED** [review]

**Comment by lutangar** [comment]
I thought there was an unhandled `exception` left somewhere when the backend wasn't reachable. Does it solves this issue and catch this one? In `dev` this was easy to test, just dont start the backend and the extension crash nastily.

**Comment by JalilArfaoui** [comment]
@lutangar we were trying up to 10 times … Now with this, we’ll keep trying until network or backend recovers
